import type { Metadata } from "next";
import { Rubik, Merriweather_Sans } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
});

const merriweatherSans = Merriweather_Sans({
  subsets: ["latin"],
  variable: "--font-merriweather-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${rubik.variable} ${merriweatherSans.variable} dark`}
    >
      <body className="bg-obsidian-bg text-obsidian-fg font-sans min-h-screen">
        {children}
      </body>
    </html>
  );
}
